website/views.py
from flask import Blueprint, render_template, jsonify, request, redirect, url_for, session
from flask_login import login_required, current_user
from . import db
import uuid
from .decorators import user_required, doctor_required
from .models import Doctor
from .auth import get_current_user

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("index.html", user=current_user)


@views.route('/all_doctors')
def doctors():
    return render_template("doctors.html", user=current_user)

@views.route('/doctor_dashboard/<doctor_id>')
@doctor_required
def doctor_dashboard(doctor_id):
    current_user_info = get_current_user()
    user_type = current_user_info['type']
    return render_template("doctor_dashboard.html", user=current_user, doctor_id=doctor_id, user_type=user_type)

@views.route('/chat/<room_code>/<doctor_id>')
@login_required
def chat(room_code, doctor_id):
    doctor = Doctor.query.filter_by(doctorID=doctor_id).first()
    current_user_info = get_current_user()
    user_type = current_user_info['type']
    return render_template("chat.html", user=current_user, doctor=doctor, room_code=room_code, user_type=user_type)

rooms = []

@views.route('/generate_room/<doctor_id>', methods=['POST'])
@user_required
def generate_room(doctor_id):
    while True:
        room_code = str(uuid.uuid4())
        if room_code not in rooms:
            # Save room_code to the database if needed
            return jsonify({
                'room_code': room_code,
                'doctor_id':doctor_id
            })
        else:
            continue

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="/static/styles.css">    
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
      integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
      crossorigin="anonymous"></script>    
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" type="module" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous" defer></script>  
    <script src="/static/main.js" defer></script>
    <title> {% block title %} {% endblock %} </title>
</head>
<body>

    <div class="tab-container">
        <div class="heading">IntimateQ</div>
        <div class="burger-menu">
            <img src="/static/assets/burger.svg" alt="burger menu icon">
        </div>
        <div class="tab-bar">
            <div class="tab"><a href="/">Home</a></div>
            <!-- <div class="tab">About Us</div> -->
            <!-- <div class="tab">Testimonials</div> -->
            <div class="tab" data-section-id="#contact">Contact</div>
            {% if user_type == 'user' %}
                <div class="tab"><a href="{{ url_for('views.doctors') }}">Doctors</a></div>
            {% endif %}
            {% if user.is_authenticated %}
                {% if user_type == 'doctor' %}
                    <div class="tab"><a href="{{ url_for('views.doctor_dashboard', doctor_id=user.doctorID) }}">Dashboard</a></div>
                {% endif %}
            <div class="tab" ><a href="/logout">Logout</a></div>
            {% else %}
            <div class="tab" ><a href="/login">Login</a></div>
            <div class="tab"><a href="/register">Register</a></div>
            <div class="tab"><a href="/doctor_login">Doctor Login</a></div>
            {% endif %}
        </div>
    </div>

    {% block content %} {% endblock %}
</body>
</html>

website/templates/chat.html
{% extends 'base.html' %}

{% block title %}
    Chat
{% endblock %}

{% block content %}

    <div class="form-container">
        <div class="chat-container form">
            <h1>Chat</h1>
            <div id="chat-window">
                <div id="messages">
                    {% for msg in messages %}
                    <div class="message">
                        <strong>{{ msg.name }}:</strong> {{ msg.message }}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="chat-bottom">
                <input type="text" id="chat-message" placeholder="Type a message...">
                <button id="send-message-btn">Send</button>
            </div>
        </div>
    </div>

    

    <script type="text/javascript" defer>
        const sockets = [
            io('wss://intimateq.onrender.com', {
                path: '/socket.io',
                transports: ['websocket']
            }),
            io('https://intimateq.in', {
                path: '/socket.io',
                transports: ['websocket']
            }),
            io('https://www.intimateq.in', {
                path: '/socket.io',
                transports: ['websocket']
            })
        ];
        

        const userType = "{{ user_type }}";        
        const roomCode = "{{ room_code }}";        
        const messages = document.getElementById('chat-window');

        sockets.forEach(socket => {
            socket.emit('join', roomCode);

            socket.on('message', function(content) {
                createMessage(content.name, content.message);
            });
        });


        function createMessage(name, msg) {
            const content = `
                <div>
                    <strong>${name}</strong>: ${msg}
                </div>
            `;
            messages.innerHTML += content;
        }


        function sendMessage() {
            const messageInput = document.getElementById('chat-message');
            const message = messageInput.value;
            if (message === "") return;            
            const content = {
                "room": roomCode,
                "message": message
            } 
            sockets.forEach(socket => {
                socket.emit('message', content);
            });
            
            if (userType === 'user') {
                const userId = '{{ user.id }}';    
                const username = "{{ user.username }}";  
                sockets.forEach(socket => {
                    socket.emit('chat_request', { 'room': roomCode, 'userId': userId, "message": message });
                });
            }
            messageInput.value = '';
        }

        document.getElementById('send-message-btn').addEventListener('click', function() {
            sendMessage();
        });
    </script>
    

{% endblock %}

website/templates/doctor_dashboard.html
{% extends 'base.html' %}

{% block title %}
    Doctor Dashboard
{% endblock %}

{% block content %}

    <div class="container">
        <h1>Doctor Page</h1>
        <div id="chat-requests"></div>
    </div>

    <script defer>
        const sockets = [
            io('wss://intimateq.onrender.com', {
                path: '/socket.io',
                transports: ['websocket']
            }),
            io('https://intimateq.in', {
                path: '/socket.io',
                transports: ['websocket']
            }),
            io('https://www.intimateq.in', {
                path: '/socket.io',
                transports: ['websocket']
            })
        ];

        const doctorID = '{{ doctor_id }}';

        sockets.forEach(socket => {
            socket.on('chat_request', function(data) {
                const chatRequests = $('#chat-requests');
                const requestDiv = $(`
                    <div class="chat-request">
                        <p>Chat request from ${data.user_json["username"]}</p>
                        <button class="join-chat-btn" data-room="${data.room}">Join Chat</button>
                    </div>
                `);
                chatRequests.append(requestDiv); 
            });
        });


        document.getElementById('chat-requests').addEventListener('click', function(event) {
            if (event.target && event.target.classList.contains('join-chat-btn')) {
                const room = event.target.getAttribute('data-room');
                window.location.href = `/chat/${room}/${doctorID}`;
            }
        });
    </script>

{% endblock %}

website/templates/doctor_login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}

    <div class="form-container">
        <h1 class="form-heading">Doctor Login</h1>
        <div class="form-wrapper">
            <form action="/doctor_login" method="post" class="form">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" required>
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required>
                <button type="submit">Login</button>
            </form>
        </div>
    </div>

{% endblock %}

website/templates/doctor_register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content %}

    <h1>Register</h1>
    <form action="/doctor_register" method="post">
        <label for="doctorID">Doctor ID</label>
        <input type="text" name="doctorID" id="doctorID" required>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required>
        <label for="username">Username</label>
        <input type="text" name="username" id="username" required>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required>
        <button type="submit">Login</button>
    </form>

{% endblock %}

website/templates/doctors.html
{% extends 'base.html' %}

{% block title %}
    Doctors
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Doctors</h1>
        <div class="doctors">
            <div class="wrapper">
                <div class="doctors-card">
                    <div class="doctor" data-doctor-id="12345">                    
                        <img src="../static/assets/doc1.png" alt="doctor" class="doctor-image">                    
                        <div class="overlay">                        
                            <div class="doctor-name">Dr. Srijana Saha</div>
                            <div class="doctor-specialization">Dept of Head - Neck Surgery</div>
                            <div class="doctor-qualification">MBBS, MS ENT, DNB ENT</div>     
                            <div class="doctor-consult-btn">Consult</div>                                                   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block title %} IntimateQ {% endblock %}

{% block content %}

    

    <div class="logo-wrapper">
        <img src="../static/assets/icon.svg" alt="logo" id="logo">   
    </div>

    <div class="content-wrapper">
        <section id="homepage" class="section">
            <div class="slogan">Your Incognito Tab!</div>
            <div class="chat-btn">Start a new chat</div>
        </section>

        <div id="chat-scroll-btn"><img src="../static/assets/chat.svg" alt="chat image"></div>
    
        <section id="services" class="section">
            <div class="subheading" id="services-subheading">Our Services</div>
            <div class="services-container">
                <div class="service">
                    <div class="lines"></div>
                    <div class="service-icon">
                        <img src="../static/assets/qna.svg" alt="QnA image">
                    </div>
                    <div class="content">
                        <div class="details">
                            <div class="service-title">Q&A Platform</div>
                            <div class="service-description">Consult with our doctors and get the best advice</div>
                        </div>
                    </div>
                </div>                
                <div class="service">
                    <div class="lines"></div>
                    <div class="service-icon">
                        <img src="../static/assets/webinar.svg" alt="webinar image">
                    </div>
                    <div class="content">
                        <div class="details">
                            <div class="service-title">Webinars and Workshops</div>
                            <div class="service-description">Join our interactive sessions for in-depth learning</div>
                        </div>
                    </div>
                </div>                
                <div class="service">
                    <div class="lines"></div>
                    <div class="service-icon">
                        <img src="../static/assets/educational.svg" alt="educational image">
                    </div>
                    <div class="content">
                        <div class="details">
                            <div class="service-title">Educational Resources</div>
                            <div class="service-description">Explore articles, videos, and guides on various topics</div>
                        </div>
                    </div>
                </div>                
                <div class="service">
                    <div class="lines"></div>
                    <div class="service-icon">
                        <img src="../static/assets/personalised.svg" alt="personalised image">
                    </div>
                    <div class="content">
                        <div class="details">
                            <div class="service-title">Personalized Guidance</div>
                            <div class="service-description">Get one-on-one support from certified doctors</div>
                        </div>
                    </div>
                </div>                
                
            </div>               
        </section>
    
        <section id="doctors" class="section">
            <div class="subheading" id="doctors-subheading">Our Trusted Doctor</div>
            <div class="wrapper">
                <div class="doctors-card">
                    <div class="doctor">                    
                        <img src="../static/assets/doc1.png" alt="doctor" class="doctor-image">                    
                        <div class="overlay">                        
                            <div class="doctor-name">Dr. Srijana Saha</div>
                            <div class="doctor-specialization">Dept of Head - Neck Surgery</div>
                            <div class="doctor-qualification">MBBS, MS ENT, DNB ENT</div>     
                            <!-- <div class="doctor-consult-btn">Consult</div>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="see-all-btn">See All Doctors <img src="../static/assets/new_tab.svg" alt="new tab img"></div>
        </section>
    
        <section id="why-us" class="section">
            <div class="subheading" id="why-us-subheading">Why Us</div>
            <div class="why-us-container">
                <div class="why-us-card">
                    <div class="overlay">
                        <div class="why-us-title">Professional Answers</div>
                        <div class="why-us-description">Message and video chat with certified professional and get accurate and reliable answers for your queries</div>
                    </div>
                </div>                
                <div class="why-us-card">
                    <div class="overlay">
                        <div class="why-us-title">Safe environment</div>
                        <div class="why-us-description">Feel to share anonymously your personal questions. This is a judgement free space designed for comfort and privacy ensuring wellbeing of young minds </div>
                    </div>
                </div>                
                <div class="why-us-card">
                    <div class="overlay">
                        <div class="why-us-title">Comprehensive Knowledge</div>
                        <div class="why-us-description">Get access to a wide range of questions and topics that arise among teenagers that are tailored to your needs specifically.</div>
                    </div>
                </div>                
            </div>
        </section>
    
        <section id="contact" class="section">
            <div>
                <div id="feedback">
                    <div class="feedback-heading">Feedback</div>
                    <div class="feedback-form">
                        <label for="name">Name:</label>
                        <input type="name" name="name" id="name" placeholder="Enter your name">
                        <label for="email">Email:</label>
                        <input type="email" name="email" id="email" placeholder="Enter your email">
                        <label for="feedback-text">Feedback:</label>
                        <textarea type="text" id="feedback-text" placeholder="Please provide feedback"></textarea>
                        <div class="feedback-submit">Submit</div>
                    </div>            
                </div>
                <div class="contact-right">
                    <div id="get-involved">
                        <div class="get-involved-heading">Get Involved</div>
                        <div class="get-involved-text">
                            <div class="get-involved-title">Join the Community</div>
                            <div class="get-involved-description">Sign up to participate in discussions and access exclusive content.</div>
                        </div>
                        <div class="get-involved-text">
                            <div class="get-involved-title">Attend Events</div>
                            <div class="get-involved-description">Check our calendar for upcoming webinars and workshops.</div>
                        </div>
                        <div class="get-involved-text">
                            <div class="get-involved-title">Partner with Us</div>
                            <div class="get-involved-description">Learn how schools, NGOs, and other organizations can collaborate with IntimateQ.</div>
                        </div>
                        <div class="get-involved-ending">
                            Start your journey with IntimateQ today and empower yourself with knowledge. Explore our resources, ask your questions, and take control of your sexual health with confidence.
                        </div>
                    </div>
                    <div class="contact-container">
                        <div class="contact-sunheading">Contact Us</div>
                        <div class="contact-intro">
                            Have questions or need support? Reach out to us at <a href="mailto:contact@intimateq.com">contact@intimateq.com</a> or follow us on social media for updates and information.
                        </div>
                        <div class="contact-card">                            
                            <a href="#" target="_blank"><i class='bx bxl-facebook'></i></a>
                            <a href="#" target="_blank"><i class='bx bxl-linkedin' ></i></a>
                            <a href="#" target="_blank"><i class='bx bxl-instagram' ></i></a>
                            <a href="#" target="_blank"><i class='bx bxl-twitter'></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}

    <div class="form-container">
        <h1 class="form-heading" >User Login</h1>
        <div class="form-wrapper">
            <form action="/login" method="post" class="form">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" required>
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required>
                <button type="submit">Login</button>
            </form>
        </div>
    </div>

{% endblock %}

website/templates/register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content %}

    <div class="form-container">
        <h1 class="form-heading">User Register</h1>
        <div class="form-wrapper" id="register-form-wrapper">
            <form action="/register" method="post" class="form" >
                <label for="email">Email</label>
                <input type="email" name="email" id="email" required>
                <label for="username">Username</label>
                <input type="text" name="username" id="username" required>
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required>
                <label for="date-of-birth">Date of Birth</label>
                <input type="date" name="date-of-birth" id="date-of-birth" required>
                <label for="gender">Gender</label>
                <select name="gender" id="gender">
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                    <option value="other">Other</option>
                </select>
                <button type="submit">Register</button>
            </form>
        </div>
    </div>

{% endblock %}